app:
 image: jaequery/honeybadger
 links:
 - db:honeybadger-postgres
 command: /init_container.sh
 environment:
 - VIRTUAL_HOST=honeybadger.app,honeybadger.jaequery.com
 restart: always
 volumes:
   - .:/app
   - ./Docker/init_container.sh:/init_container.sh
db:
 image: postgres
 environment:
 - POSTGRES_PASSWORD=j
 restart: always
