app:
 image: jaequery/honeybadger
 links:
 - db:honeybadger-postgres
 command: /init_container.sh
 environment:
 - VIRTUAL_HOST=honeybadger.app,honeybadger.jaequery.com
 restart: always
 volumes:
   - .:/app
   - ./Docker/init_container.sh:/init_container.sh
db:
 image: postgres
 environment:
 - POSTGRES_PASSWORD=j
 restart: always
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock