app:
 image: ruby:2.1-onbuild
 links:
 - db:honeybadger-postgres
 command: Docker/init_container.sh
 environment:
 - VIRTUAL_HOST=honeybadger.app
 ports: 
 - "3000"
 volumes:
 - .:/usr/src/app
 tty: true
db:
 image: postgres
 environment:
 - POSTGRES_PASSWORD=j

